const languages = {
  ar: {
    Home: "الريئسية",
    OurMession: "مهمتنا",
    ourMessionSubtitle: "استصلاح الصحراء لتوفير الأمن الغذائي",
    OurProjects: "مشاريعنا",
    WhoWeAre: "فريقنا",
    callUs: "تواصل معنا",
    PositionThatWillSuitYou: " اختر الوظيفة التي تناسبك",
    partners: "شركائنا",
    partnersSubtitle: "شركاء فى الاستصلاح. شركاء فى النجاح",
    intro:
      "الاستثمارات بعيدة المدى رؤيتنا, والأمن الغذائي والإنتاج الحيوانى هدفنا",
    aboutUsTitle: "مهمتنا",
    aboutUsSubTitle: "تعرف على الفريق وراء فيض النعم",
    subNavProjects: "شاهد أجدد مشريعنا",
    subNavContactUs: " أطلب عرض",
    subNavTitle: "استكشف المزيد",
    aboutUsParagraph: `أن  تصبح شركة فيض النعم رائدة في المجال الزراعي والإنتاج الحيواني في مصر . تلتزم شركة فيض النعم بالاستغلال الأمثل للموارد

        والحفاظ على البيئة وتقديم منتجات عالية الجودة ومستدامة من خلال استصلاح الأراضي ومشاريع الإنتاج الزراعي والحيواني وتساهم
        
        بشكل فعال في الاقتصاد المصري والعالمي لتكملة مشروعات الأمن الغذائي والإنتاج الحيواني والرؤية الاستثمارية بعيدة المدى وتبعا
        
        للمتطلبات العالمية للغذاء 
        `,
    projectsTitle: "عازمون على مشاريع مستدامة، نرسم مستقبل ملهم",
    testimonials: "شهادات عملائنا",
    testimonialsSubTitle: "شهادات عملائنا تعكس رضاهم",
    contactUsSubTitle: "زورونا أو أرسلوا أسئلتكم للمساعدكم",
    servicesTitle: "خدماتنا",
    servicesSubTitle: "بخدماتنا، تتحول الإلهام إلى عمل",
    careers: "وظائف",
    Submit: "ارسال",
    careersParagraph:
      "هل أنت متحمس لإحداث فرق؟ نحن دائمًا نبحث عن مواهب مميزة للانضمام إلى فريقنا المتنامي. في فيض النعم ، ستتاح لك الفرصة للتعاون مع رواد الصناعة ، ومعالجة المشكلات الصعبة ، والمساهمة في مشاريع مبتكرة تشكل المستقبل. نقدم حزمة تعويضات تنافسية وبيئة عمل ديناميكية تعزز الإبداع والنمو المهني. تصفح الوظائف الشاغرة لدينا واكتشف ما إذا كانت الفرصة الوظيفية المثالية لك تنتظرك",
    finished: "ادي الخدمة العسكرية",
    exempted: "معفي",
    delayed: "متاخر",
    inReserve: "في الاحتياط",
    male: "ذكر",
    female: "انثي",
    militaryStatus: "حالة الخدمة العسكرية",
    gender: "الجنس",
    didntFindJobP:
      "لم تجد الوظيفة المناسبة لك اليوم؟ نحن ننمو باستمرار، لذا ترقب المزيد من الوظائف الشاغرة التي تتوافق مع مهاراتك. في هذه الأثناء، يمكنك تحميل سيرتك الذاتية وسنطلعك على الفرص ذات الصلة ",

    FullName: "الأسم رباعي",
    FullAddress:
      "عنوانك بالتفصيل : رقم العمارة, اسم الشارع, الحى , المدينة, المحافظة",
    Nationality: "الجنسية",
    Religion: "الديانة",
    PhoneNumber: "رقم الموبايل",
    EmailAddress: "example@example.com",
    Age: "العمر",
    DateOfBirth: " تاريخ الميلاد",
    Gender: "الجنس",
    Male: "رجل",
    Female: "امرأة",
    MilitaryStatus: "حالة الخدمة العسكرية",
    Finished: "أديت الخدمة العسكرية",
    Exempted: "معفى",
    Delayed: "أجلت",
    YourPersonalData: " البيانات الشخصية",
    companyName: "فيض النعم للامن الغذائي",
    InReserve: "لم أؤدى الخدمة العسكرية",
    YourEducationAndTrainings: "التعليم والتدريبات",
    AllDataAreRequired: "يجب املأ كل الخانات",
    University: "الجامعة/الأكاديمية",
    Faculty: "الكلية/المعهد",
    Grade: "التقدير",
    GraduationYear: "سنة التخرج",
    CoursesAndTrainingsSection: "الكورسات والتدريبات",
    CourseName: "اسم التدريب/الكورس",
    Institute: "المنظمة/الموقع",
    From: "من",
    To: "الى",
    Address:
      " العنوان بالتفصيل : رقم العمارة, اسم الشارع, الحى , المدينة, المحافظة",

    YourExperiences: "خبراتك",
    CompanyName: "اسم الشركة",
    CompanyAddress: "عنوان الشركة",
    Position: "الوظيفة",
    WhatIsYourRoles: "تعريف عن الوظيفة مبسط",
    YourResumeAndCoverLetter: "السيرة الذاتية وخطاب التغطية",
    CoverLetter: "خطاب التغطية",
    NoFileSelected: "لم يتم اختيار ملف",
    YouAppliedFor: " لقد قمت بالتقديم على ",
    pleaseFillTheForm: " برجاء تعبئة النموذج",
    availableJobs: "الوظائف المتاحة",
    CheckForAvailableJobs: " التحقق من الوظائف المتاحة",
    UploadYourResume: " ارفع سيرتك الذاتية",
    ApplyYourResume: " التقديم على سيرتك الذاتية",
    SelectResume: " اختيار السيرة الذاتية",
    careersSubP:
      "فيض النعم تبحث عن مواهب متحمسة للانضمام إلى فريقها المتنامي. اعمل مع رواد الصناعة على مشكلات صعبة ومشاريع مبتكرة تشكل المستقبل! اطلع على وظائفنا المتاحة.",
      NoCareersP: `تهتم مجموعة فيض النعم دائمًا بتوظيف الأشخاص المتميزين مع مجموعة من الخلفيات المتنوعة. ما نبحث عنه هم الأشخاص الذين يتمتعون بالإبداع والتزام وعقليات تحليلية وإمكانيات قيادية.
      نبحث باستمرار عن مواهب جديدة لتعزيز فريقنا. إذا كنت مهتمًا بمسار مهني معنا، فيرجى تحميل سيرتك الذاتية أو إرسالها إلى البريد الإلكتروني:`,
    },
  eng: {
   companyName: " Faid Al-Naam For Food Security",
    careersSubP:
      "Faid Al  Naam is seeking passionate individuals to join their growing team.  Work with industry leaders on challenging problems and innovative projects that shape the future!. Check our job vacancies.",
    NoCareersP: ` Our team of experts are committed to finding new and exciting opportunities. What we're looking for is a group of people who are passionate about innovation, excellence, and critical thinking.`,
    Home: "Home",
    OurMession: "Our mission",
    ourMessionSubtitle: "Desert reclamation to ensure food security",
    OurProjects: "Our Projects",
    WhoWeAre: "Our Team",
    callUs: "Contact Us",
    PositionThatWillSuitYou: "Choose a Vacancy that will suit you",

    partners: "Partners",
    partnersSubtitle: "Partners in reclamation. Partners in success.",
    intro:
      "Long-term investments are our vision. Food security and animal production are our goals.",
    aboutUsTitle: "Our mission",
    aboutUsSubTitle: "Meet the passionate team behind Faid Al-Naam",
    subNavProjects: "See our latest projects",
    subNavContactUs: "REQUEST A BID",
    subNavTitle: "Explore more",
    aboutUsParagraph:
      "To become a pioneer in the field of agriculture and animal production in Egypt. Faydh Al-Naam Company is committed to the optimal utilization of resources, environmental conservation, and providing high-quality and sustainable products through land reclamation, agricultural and livestock production projects. It effectively contributes to the Egyptian and global economy to complement food security, livestock production, and long-term investment vision, in line with global food requirements.",
    projectsTitle:
      "Determined for sustainable projects, we paint an inspiring future.",
    testimonials: "Our clients testimonials",
    testimonialsSubTitle:
      "Our clients testimonials showcase their satisfaction.",
    contactUsSubTitle: "Visit us or send your questions for your assistance.",
    servicesTitle: "Our services.",
    servicesSubTitle: "With our services, inspiration becomes action",
    careers: "Careers",
    careersParagraph:
      "Are you passionate about making a difference? We're always looking for talented individuals to join our growing team. At Faid Al Naam, you'll have the opportunity to collaborate with industry leaders, tackle challenging problems, and contribute to innovative projects that shape the future.  We offer a competitive compensation package and a dynamic work environment that fosters creativity and professional growth.  Browse our open positions and see if your perfect career fit is waiting!",
    finished: "Finished",
    CheckForAvailableJobs: "Check for available jobs",
    exempted: "Exempted",
    delayed: "Delayed",
    inReserve: "In Reserve",
    male: "Male",
    female: "Female",
    militaryStatus: "Military Status",
    gender: "Gender",
    YouAppliedFor: "You applied for",
    didntFindJobP:
      "Didn't see your perfect match today? We're constantly growing, so keep an eye out for new openings that align with your skills. In the meantime, you can upload your resume and we'll keep you informed of relevant opportunities",
    FullName: "Full name",
    UploadYourResume: "Upload your resume",
    Address:
      " Address : Building number, street name, neighborhood, city, province",
    Nationality: "Nationality",
    Religion: "Religion",
    PhoneNumber: "Phone number",
    EmailAddress: "example@example.com",
    Age: "Age",
    DateOfBirth: " Date of birth",
    Gender: "Gender",
    Male: "Male",
    Female: "Female",
    MilitaryStatus: "Military status",
    Finished: "Finished",
    Exempted: "Exempted",
    Delayed: "On hold",
    InReserve: "In reserve",
    YourEducationAndTrainings: "Your Education and trainings",
    AllDataAreRequired: "All data are required",
    University: "University",
    Faculty: "Faculty",
    Grade: "Grade",
    GraduationYear: "Graduation year",
    CoursesAndTrainingsSection: "Courses and training",
    CourseName: "Course name",
    Institute: "Institute",
    From: "From",
    To: "To",
    Submit: "Submit",
    SelectResume: "Select resume",
    YourPersonalData: "Your personal data",
    YourExperiences: "Your experiences",
    CompanyName: "Company name",
    CompanyAddress: "Company address",
    Position: "Position",
    WhatIsYourRoles: "What is your roles",
    YourResumeAndCoverLetter: "Resume and cover letter",
    CoverLetter: "Cover letter",
    NoFileSelected: "No file selected",
    pleaseFillTheForm: "position, Please fill the form",
    availableJobs: "Available jobs",
    ApplyYourResume: "Apply your resume",
  },
};

export default languages;
