import { useTranslations } from "next-intl";
import Input from "../components/input";
import { Metadata } from "next";
export const metadata: Metadata = {
    title: "aaaa",
    description: "Generated by create next app",
    
  };
export default function Projects(){
     const  t  = useTranslations("");
    // const router = useRouter();
    // const { locale, slug } = router.query;
    // console.log(locale, slug);
    return (<>
    <h2>{t('OurMession')}</h2>
    <Input/>
    </>)
}